#!/bin/bash
#
# htmlDefuse (Timo Felbinger, 2011 .. 2013)
#
# this script is an ExtFilter for apache:
#
# the script will gobble all lines up to and including a line starting with
#   extfilter:
# followed by a filter type keyword. currently supported:
# - null: a null filter to just pass through any remaining lines
# - html: an outfilter for html which will
#   * quote HTML "hot" characters (', ", <, > and &) as  &...; -entities
#   * convert ASCII characters 0x11...0x15 to hot characters ' ... & 
# - divert: an outfilter to conditionally divert output: output will be started by a line matching
#        /^\x14\x14\x14$/
#   and will be suppressed by a line matching; initial mode is "suppressed"
#        /^\x13\x13\x13$/
#   s/^\x11// will be applied to all printed output, which can be used for escaping if there is any
#   risk of the above patterns to appear in the output
#
# the html filter is supposed to prevent ccs attacks in web applications:
# - reject characters 0x11...0x15 in user (text) input (they serve no useful purpose
#   there, and can be easily and unambiguously detected in an utf8 input stream)
# - use 0x11...0x15 to represent ' ... & in HTML output produced from cgi scripts
# - configure apache to use this script as output filter (see ExtFilterDefine)
#
# it may be a good idea to include a plain-text hint to switch on this filter in html
# output before the extfilter line.
# 
extfilter='error'
while read tag f; do
  if [ "$tag" = 'extfilter:' ] ; then
    extfilter="$f"
    break
  fi
done

case "$extfilter" in
  error )
    echo "fatal error - script died early and no valid output was produced, sorry!";
  ;;
  null )
    dd
  ;;
  divert )
    sed -n -e $'
      :skip
        /^\x14\x14\x14$/b print
        n
        b skip
      :print
        n
        /^\x13\x13\x13$/b skip
        s/^\x11//
        p
        b print
    '
  ;;
  html )
    sed -n -e "
      :defuse
        s/&/\&amp;/g
        s/'/\&#039;/g
        s/\"/\&quot;/g
        s/</\&lt;/g
        s/>/\&gt;/g
        p
        n
        b defuse
    " | tr $'\x11\x12\x13\x14\x15' "'\"<>&"
  ;;
  * )
    echo "unsupported extfilter: $extfilter"
  ;;
esac

