#!/bin/bash
#
# htmlDefuse (Timo Felbinger, 2011)
#
# this script is an ExtFilter for apache and will
# - quote HTML "hot" characters (', ", <, > and &) as  &...; -entities
# - convert ASCII characters 0x11...0x15 to hot characters ' ... & 
# - the script will discard all lines up to the line starting with
#     <!DOCTYPE HTML 
#   (this allows to include a plain-text hint to switch on this filter in html output)
#
# this filter is supposed to prevent ccs attacks in web applications:
# - reject characters 0x11...0x15 in user (text) input (they serve no useful purpose
#   there, and can be easily and unambiguously detected in an utf8 input stream)
# - use 0x11...0x15 to represent ' ... & in HTML output produced from cgi scripts
# - configure apache to use this script as output filter (see ExtFilterDefine)
#
# 
while read tag format; do
  if [ "$tag" = 'format:' ] ; then
    break
  fi
done

case "$format" in
  pdf | csv )
    dd
  ;;
  html )
    sed -n -e "
      :defuse
        s/&/\&amp;/g
        s/'/\&#039;/g
        s/\"/\&quot;/g
        s/</\&lt;/g
        s/>/\&gt;/g
        p
        n
        b defuse
    " | tr $'\x11\x12\x13\x14\x15' "'\"<>&"
  ;;
  * )
    echo "unsupported format: $format"
  ;;
esac

