#!/usr/local/bin/php
<?php

echo "cl: start\n";

$global_format = 'cgi';
$header_printed = true; //no header required

require_once('cl/cl_common.php');
require_once('cl/cl_commands.php');

switch( $argv[ 1 ][ 0 ] ) {
  case 'q':
    cl_query( $argv[ 2 ] );
    break;
  case 'i':
    echo cl_insert( $argv[ 2 ] );
    break;
  case 'u':
    echo cl_update( $argv[ 2 ], $argv[ 3 ] );
    break;
  case 's':
    echo cl_sql( $argv[ 2 ] );
    break;
}

echo "\ncl: end\n";


?>
