#!/usr/local/bin/php
<?php
// 
//  cl
// 
//  php script to be called via command line interface (not through apache)
//  it will obtain db config from environment and should be called from cl.sh
//  
//  syntax:
//    cl [<opt>...]command table [<filter>] 
//
$debug = 1;
$_GET = array( 'f' => 'cli' );

// $header_printed = true; //no header required

require_once('cl/cl_common.php');

$args = explode( '.', $argv[ 1 ] . '.........' );
foreach( $args as & $ref_a ) {
  if( $ref_a ) {
    $ref_a = hex_decode( $ref_a );
    need( check_utf8( $ref_a ), 'cli argument: not valid utf-8' );
  }
}
unset( $ref_a );
$do_echo = false;
$verbose = false;
$command = $args[ 1 ];

while( true ) {
  // debug( $command, 'parsing:' );
  switch( $command[ 0 ] ) {
    case 'v':
      $verbose = true;
      $command = substr( $command, 1 );
      echo "cl: start: $utc\n";
      continue 2;
    case 'e':
      $do_echo = true;
      $command = substr( $command, 1 );
      continue 2;
    case 'q':
      cl_query( $args );
      break;
    case 'i':
      echo cl_insert( $args[ 2 ] );
      break;
    case 'u':
      echo cl_update( $args[ 2 ], $args[ 3 ] );
      break;
    case 's':
      echo cl_sql( $args[ 2 ] );
      break;
    default:
      echo "invalid command\n";
      break;
  }
  break;
}

if( $verbose ) {
  echo "cl: end: " . datetime_unix2canonical( time() );
}

sql_do( 'COMMIT AND NO CHAIN' );

?>
